### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by forhadkhan** [howtocode-com-bd/git.howtocode.com.bd#23]
The [URL](https://git.howtocode.com.bd/) that added in the about section is not working in my case. Please have a look if any problem there.

1.
![image](https://user-images.githubusercontent.com/67508944/101262242-59a3d380-3767-11eb-899d-4a0d4af24e75.png)

2. 
![image](https://user-images.githubusercontent.com/67508944/101262260-74764800-3767-11eb-97f9-4e9c75e045ce.png)

**Comment by FahimFBA** [comment]
Same here

**Comment by howtocode-dev** [comment]
All the urls should be .dev
We have updated the about section as well.
